version: 1.0

snow:
  - id: 546046 # Milo Bacom (business.adobe.com)

notifications:
  jira:
    default:
      project: MWPW # Mandatory
      filters:
        include:
          risk_rating: R5
      fields:
        assignee:
          name: slavin
        customfield_11800: MWPW-140779 #epic link
        customfield_12900:  
          value: Magma
        watchers:
          - casalino
          - jmichnow
          - mauchley
          - bmarshal
          - methomas
        labels:
          - "OriginatingProcess=Kodiak"
          - "security"
          - "kodiak-ticket"
        components:
          - name: "DevOps Security"
